version: '3.7'
services:
  postgres:
    container_name: postgres-easyvsl
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_SCHEMA}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

